version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=vpiusr
      - POSTGRES_PASSWORD=Seatt!3
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
